# Generated by Django 5.1.2 on 2024-11-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewPortal', '0002_student_profile_type_alter_student_cwid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
