# Generated by Django 5.1.2 on 2024-11-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewPortal', '0010_rename_primary_email_email_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email_type',
            field=models.CharField(choices=[('L', 'Local'), ('P', 'Permanent')], max_length=10, null=True),
        ),
    ]
