# Generated by Django 5.1.2 on 2024-12-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewPortal', '0013_remove_student_academic_dept_remove_student_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='current_profile',
            field=models.CharField(choices=[('C', 'Curernt'), ('P', 'Past')], default='Current', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profiles',
            name='academic_dept',
            field=models.CharField(choices=[('sch', 'Scahefer'), ('bus', 'Business')], max_length=10),
        ),
    ]
