# Generated by Django 5.1.2 on 2024-12-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewPortal', '0014_profiles_current_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledocument',
            name='name',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
