# Generated by Django 5.1.2 on 2024-12-05 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewPortal', '0015_profiledocument_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkAuthorizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_type', models.CharField(choices=[('C', 'CPT'), ('O', 'OPT')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('request_status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected'), ('C', 'Cancelled')], max_length=10)),
                ('time_type', models.CharField(choices=[('F', 'Full Time'), ('P', 'Part Time')], max_length=10)),
                ('work_months', models.IntegerField()),
                ('student_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='renewPortal.student')),
            ],
        ),
        migrations.CreateModel(
            name='AuthDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_file', models.FileField(upload_to='documents/authorizations/')),
                ('name', models.CharField(max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('work_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_documents', to='renewPortal.workauthorizations')),
            ],
        ),
    ]
