# Generated by Django 5.1.2 on 2024-12-06 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewPortal', '0016_workauthorizations_authdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_of_entry', models.CharField(max_length=10)),
                ('registration', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_file', models.FileField(upload_to='documents/student_docs/')),
                ('title', models.CharField(max_length=200)),
                ('keywords', models.CharField(max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(max_length=200)),
                ('context', models.CharField(choices=[('G', 'General'), ('S', 'Special')], max_length=10)),
                ('student_docs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='renewPortal.student')),
            ],
        ),
    ]
