# Generated by Django 5.1.2 on 2024-12-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewPortal', '0018_interactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='bulk/csv/')),
            ],
        ),
    ]
