# Generated by Django 5.1.2 on 2024-12-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewPortal', '0020_student_citizenship_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='citizenship_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='city_of_birth',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='country_of_birth',
            field=models.CharField(blank=True, choices=[('AF', 'Afghanistan'), ('AX', '"Ã…land Islands"'), ('AL', 'Albania'), ('DZ', 'Algeria'), ('AS', '"American Samoa"'), ('AD', 'Andorra'), ('AO', 'Angola'), ('AI', 'Anguilla'), ('AQ', 'Antarctica'), ('AG', '"Antigua & Barbuda"'), ('AR', 'Argentina'), ('AM', 'Armenia'), ('AW', 'Aruba'), ('AU', 'Australia'), ('AT', 'Austria'), ('AZ', 'Azerbaijan'), ('BS', 'Bahamas'), ('BH', 'Bahrain'), ('BD', 'Bangladesh'), ('BB', 'Barbados'), ('BY', 'Belarus'), ('BE', 'Belgium'), ('BZ', 'Belize'), ('BJ', 'Benin'), ('BM', 'Bermuda'), ('BT', 'Bhutan'), ('BO', 'Bolivia'), ('BA', '"Bosnia & Herzegovina"'), ('BW', 'Botswana'), ('BV', '"Bouvet Island"'), ('BR', 'Brazil'), ('IO', '"British Indian Ocean Territory"'), ('VG', '"British Virgin Islands"'), ('BN', 'Brunei'), ('BG', 'Bulgaria'), ('BF', '"Burkina Faso"'), ('BI', 'Burundi'), ('KH', 'Cambodia'), ('CM', 'Cameroon'), ('CA', 'Canada'), ('CV', '"Cape Verde"'), ('BQ', '"Caribbean Netherlands"'), ('KY', '"Cayman Islands"'), ('CF', '"Central African Republic"'), ('TD', 'Chad'), ('CL', 'Chile'), ('CN', 'China'), ('CX', '"Christmas Island"'), ('CC', '"Cocos (Keeling) Islands"'), ('CO', 'Colombia'), ('KM', 'Comoros'), ('CG', '"Congo - Brazzaville"'), ('CD', '"Congo - Kinshasa"'), ('CK', '"Cook Islands"'), ('CR', '"Costa Rica"'), ('CI', '"CÃ´te dâ€™Ivoire"'), ('HR', 'Croatia'), ('CU', 'Cuba'), ('CW', 'CuraÃ§ao'), ('CY', 'Cyprus'), ('CZ', 'Czechia'), ('DK', 'Denmark'), ('DJ', 'Djibouti'), ('DM', 'Dominica'), ('DO', '"Dominican Republic"'), ('EC', 'Ecuador'), ('EG', 'Egypt'), ('SV', '"El Salvador"'), ('GQ', '"Equatorial Guinea"'), ('ER', 'Eritrea'), ('EE', 'Estonia'), ('SZ', 'Eswatini'), ('ET', 'Ethiopia'), ('FK', '"Falkland Islands"'), ('FO', '"Faroe Islands"'), ('FJ', 'Fiji'), ('FI', 'Finland'), ('FR', 'France'), ('GF', '"French Guiana"'), ('PF', '"French Polynesia"'), ('TF', '"French Southern Territories"'), ('GA', 'Gabon'), ('GM', 'Gambia'), ('GE', 'Georgia'), ('DE', 'Germany'), ('GH', 'Ghana'), ('GI', 'Gibraltar'), ('GR', 'Greece'), ('GL', 'Greenland'), ('GD', 'Grenada'), ('GP', 'Guadeloupe'), ('GU', 'Guam'), ('GT', 'Guatemala'), ('GG', 'Guernsey'), ('GN', 'Guinea'), ('GW', 'Guinea-Bissau'), ('GY', 'Guyana'), ('HT', 'Haiti'), ('HM', '"Heard & McDonald Islands"'), ('HN', 'Honduras'), ('HK', '"Hong Kong SAR China"'), ('HU', 'Hungary'), ('IS', 'Iceland'), ('IN', 'India'), ('ID', 'Indonesia'), ('IR', 'Iran'), ('IQ', 'Iraq'), ('IE', 'Ireland'), ('IM', '"Isle of Man"'), ('IL', 'Israel'), ('IT', 'Italy'), ('JM', 'Jamaica'), ('JP', 'Japan'), ('JE', 'Jersey'), ('JO', 'Jordan'), ('KZ', 'Kazakhstan'), ('KE', 'Kenya'), ('KI', 'Kiribati'), ('KW', 'Kuwait'), ('KG', 'Kyrgyzstan'), ('LA', 'Laos'), ('LV', 'Latvia'), ('LB', 'Lebanon'), ('LS', 'Lesotho'), ('LR', 'Liberia'), ('LY', 'Libya'), ('LI', 'Liechtenstein'), ('LT', 'Lithuania'), ('LU', 'Luxembourg'), ('MO', '"Macao SAR China"'), ('MG', 'Madagascar'), ('MW', 'Malawi'), ('MY', 'Malaysia'), ('MV', 'Maldives'), ('ML', 'Mali'), ('MT', 'Malta'), ('MH', '"Marshall Islands"'), ('MQ', 'Martinique'), ('MR', 'Mauritania'), ('MU', 'Mauritius'), ('YT', 'Mayotte'), ('MX', 'Mexico'), ('FM', 'Micronesia'), ('MD', 'Moldova'), ('MC', 'Monaco'), ('MN', 'Mongolia'), ('ME', 'Montenegro'), ('MS', 'Montserrat'), ('MA', 'Morocco'), ('MZ', 'Mozambique'), ('MM', '"Myanmar (Burma)"'), ('NA', 'Namibia'), ('NR', 'Nauru'), ('NP', 'Nepal'), ('NL', 'Netherlands'), ('NC', '"New Caledonia"'), ('NZ', '"New Zealand"'), ('NI', 'Nicaragua'), ('NE', 'Niger'), ('NG', 'Nigeria'), ('NU', 'Niue'), ('NF', '"Norfolk Island"'), ('KP', '"North Korea"'), ('MK', '"North Macedonia"'), ('MP', '"Northern Mariana Islands"'), ('NO', 'Norway'), ('OM', 'Oman'), ('PK', 'Pakistan'), ('PW', 'Palau'), ('PS', '"Palestinian Territories"'), ('PA', 'Panama'), ('PG', '"Papua New Guinea"'), ('PY', 'Paraguay'), ('PE', 'Peru'), ('PH', 'Philippines'), ('PN', '"Pitcairn Islands"'), ('PL', 'Poland'), ('PT', 'Portugal'), ('PR', '"Puerto Rico"'), ('QA', 'Qatar'), ('RE', 'RÃ©union'), ('RO', 'Romania'), ('RU', 'Russia'), ('RW', 'Rwanda'), ('WS', 'Samoa'), ('SM', '"San Marino"'), ('ST', '"SÃ£o TomÃ© & PrÃ\xadncipe"'), ('SA', '"Saudi Arabia"'), ('SN', 'Senegal'), ('RS', 'Serbia'), ('SC', 'Seychelles'), ('SL', '"Sierra Leone"'), ('SG', 'Singapore'), ('SX', '"Sint Maarten"'), ('SK', 'Slovakia'), ('SI', 'Slovenia'), ('SB', '"Solomon Islands"'), ('SO', 'Somalia'), ('ZA', '"South Africa"'), ('GS', '"South Georgia & South Sandwich Islands"'), ('KR', '"South Korea"'), ('SS', '"South Sudan"'), ('ES', 'Spain'), ('LK', '"Sri Lanka"'), ('BL', '"St. BarthÃ©lemy"'), ('SH', '"St. Helena"'), ('KN', '"St. Kitts & Nevis"'), ('LC', '"St. Lucia"'), ('MF', '"St. Martin"'), ('PM', '"St. Pierre & Miquelon"'), ('VC', '"St. Vincent & Grenadines"'), ('SD', 'Sudan'), ('SR', 'Suriname'), ('SJ', '"Svalbard & Jan Mayen"'), ('SE', 'Sweden'), ('CH', 'Switzerland'), ('SY', 'Syria'), ('TW', 'Taiwan'), ('TJ', 'Tajikistan'), ('TZ', 'Tanzania'), ('TH', 'Thailand'), ('TL', 'Timor-Leste'), ('TG', 'Togo'), ('TK', 'Tokelau'), ('TO', 'Tonga'), ('TT', '"Trinidad & Tobago"'), ('TN', 'Tunisia'), ('TR', 'Turkey'), ('TM', 'Turkmenistan'), ('TC', '"Turks & Caicos Islands"'), ('TV', 'Tuvalu'), ('UM', '"U.S. Outlying Islands"'), ('VI', '"U.S. Virgin Islands"'), ('UG', 'Uganda'), ('UA', 'Ukraine'), ('AE', '"United Arab Emirates"'), ('GB', '"United Kingdom"'), ('US', '"United States"'), ('UY', 'Uruguay'), ('UZ', 'Uzbekistan'), ('VU', 'Vanuatu'), ('VA', '"Vatican City"'), ('VE', 'Venezuela'), ('VN', 'Vietnam'), ('WF', '"Wallis & Futuna"'), ('EH', '"Western Sahara"'), ('YE', 'Yemen'), ('ZM', 'Zambia'), ('ZW', 'Zimbabwe')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='country_of_birth_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='country_of_citizenship',
            field=models.CharField(blank=True, choices=[('AF', 'Afghanistan'), ('AX', '"Ã…land Islands"'), ('AL', 'Albania'), ('DZ', 'Algeria'), ('AS', '"American Samoa"'), ('AD', 'Andorra'), ('AO', 'Angola'), ('AI', 'Anguilla'), ('AQ', 'Antarctica'), ('AG', '"Antigua & Barbuda"'), ('AR', 'Argentina'), ('AM', 'Armenia'), ('AW', 'Aruba'), ('AU', 'Australia'), ('AT', 'Austria'), ('AZ', 'Azerbaijan'), ('BS', 'Bahamas'), ('BH', 'Bahrain'), ('BD', 'Bangladesh'), ('BB', 'Barbados'), ('BY', 'Belarus'), ('BE', 'Belgium'), ('BZ', 'Belize'), ('BJ', 'Benin'), ('BM', 'Bermuda'), ('BT', 'Bhutan'), ('BO', 'Bolivia'), ('BA', '"Bosnia & Herzegovina"'), ('BW', 'Botswana'), ('BV', '"Bouvet Island"'), ('BR', 'Brazil'), ('IO', '"British Indian Ocean Territory"'), ('VG', '"British Virgin Islands"'), ('BN', 'Brunei'), ('BG', 'Bulgaria'), ('BF', '"Burkina Faso"'), ('BI', 'Burundi'), ('KH', 'Cambodia'), ('CM', 'Cameroon'), ('CA', 'Canada'), ('CV', '"Cape Verde"'), ('BQ', '"Caribbean Netherlands"'), ('KY', '"Cayman Islands"'), ('CF', '"Central African Republic"'), ('TD', 'Chad'), ('CL', 'Chile'), ('CN', 'China'), ('CX', '"Christmas Island"'), ('CC', '"Cocos (Keeling) Islands"'), ('CO', 'Colombia'), ('KM', 'Comoros'), ('CG', '"Congo - Brazzaville"'), ('CD', '"Congo - Kinshasa"'), ('CK', '"Cook Islands"'), ('CR', '"Costa Rica"'), ('CI', '"CÃ´te dâ€™Ivoire"'), ('HR', 'Croatia'), ('CU', 'Cuba'), ('CW', 'CuraÃ§ao'), ('CY', 'Cyprus'), ('CZ', 'Czechia'), ('DK', 'Denmark'), ('DJ', 'Djibouti'), ('DM', 'Dominica'), ('DO', '"Dominican Republic"'), ('EC', 'Ecuador'), ('EG', 'Egypt'), ('SV', '"El Salvador"'), ('GQ', '"Equatorial Guinea"'), ('ER', 'Eritrea'), ('EE', 'Estonia'), ('SZ', 'Eswatini'), ('ET', 'Ethiopia'), ('FK', '"Falkland Islands"'), ('FO', '"Faroe Islands"'), ('FJ', 'Fiji'), ('FI', 'Finland'), ('FR', 'France'), ('GF', '"French Guiana"'), ('PF', '"French Polynesia"'), ('TF', '"French Southern Territories"'), ('GA', 'Gabon'), ('GM', 'Gambia'), ('GE', 'Georgia'), ('DE', 'Germany'), ('GH', 'Ghana'), ('GI', 'Gibraltar'), ('GR', 'Greece'), ('GL', 'Greenland'), ('GD', 'Grenada'), ('GP', 'Guadeloupe'), ('GU', 'Guam'), ('GT', 'Guatemala'), ('GG', 'Guernsey'), ('GN', 'Guinea'), ('GW', 'Guinea-Bissau'), ('GY', 'Guyana'), ('HT', 'Haiti'), ('HM', '"Heard & McDonald Islands"'), ('HN', 'Honduras'), ('HK', '"Hong Kong SAR China"'), ('HU', 'Hungary'), ('IS', 'Iceland'), ('IN', 'India'), ('ID', 'Indonesia'), ('IR', 'Iran'), ('IQ', 'Iraq'), ('IE', 'Ireland'), ('IM', '"Isle of Man"'), ('IL', 'Israel'), ('IT', 'Italy'), ('JM', 'Jamaica'), ('JP', 'Japan'), ('JE', 'Jersey'), ('JO', 'Jordan'), ('KZ', 'Kazakhstan'), ('KE', 'Kenya'), ('KI', 'Kiribati'), ('KW', 'Kuwait'), ('KG', 'Kyrgyzstan'), ('LA', 'Laos'), ('LV', 'Latvia'), ('LB', 'Lebanon'), ('LS', 'Lesotho'), ('LR', 'Liberia'), ('LY', 'Libya'), ('LI', 'Liechtenstein'), ('LT', 'Lithuania'), ('LU', 'Luxembourg'), ('MO', '"Macao SAR China"'), ('MG', 'Madagascar'), ('MW', 'Malawi'), ('MY', 'Malaysia'), ('MV', 'Maldives'), ('ML', 'Mali'), ('MT', 'Malta'), ('MH', '"Marshall Islands"'), ('MQ', 'Martinique'), ('MR', 'Mauritania'), ('MU', 'Mauritius'), ('YT', 'Mayotte'), ('MX', 'Mexico'), ('FM', 'Micronesia'), ('MD', 'Moldova'), ('MC', 'Monaco'), ('MN', 'Mongolia'), ('ME', 'Montenegro'), ('MS', 'Montserrat'), ('MA', 'Morocco'), ('MZ', 'Mozambique'), ('MM', '"Myanmar (Burma)"'), ('NA', 'Namibia'), ('NR', 'Nauru'), ('NP', 'Nepal'), ('NL', 'Netherlands'), ('NC', '"New Caledonia"'), ('NZ', '"New Zealand"'), ('NI', 'Nicaragua'), ('NE', 'Niger'), ('NG', 'Nigeria'), ('NU', 'Niue'), ('NF', '"Norfolk Island"'), ('KP', '"North Korea"'), ('MK', '"North Macedonia"'), ('MP', '"Northern Mariana Islands"'), ('NO', 'Norway'), ('OM', 'Oman'), ('PK', 'Pakistan'), ('PW', 'Palau'), ('PS', '"Palestinian Territories"'), ('PA', 'Panama'), ('PG', '"Papua New Guinea"'), ('PY', 'Paraguay'), ('PE', 'Peru'), ('PH', 'Philippines'), ('PN', '"Pitcairn Islands"'), ('PL', 'Poland'), ('PT', 'Portugal'), ('PR', '"Puerto Rico"'), ('QA', 'Qatar'), ('RE', 'RÃ©union'), ('RO', 'Romania'), ('RU', 'Russia'), ('RW', 'Rwanda'), ('WS', 'Samoa'), ('SM', '"San Marino"'), ('ST', '"SÃ£o TomÃ© & PrÃ\xadncipe"'), ('SA', '"Saudi Arabia"'), ('SN', 'Senegal'), ('RS', 'Serbia'), ('SC', 'Seychelles'), ('SL', '"Sierra Leone"'), ('SG', 'Singapore'), ('SX', '"Sint Maarten"'), ('SK', 'Slovakia'), ('SI', 'Slovenia'), ('SB', '"Solomon Islands"'), ('SO', 'Somalia'), ('ZA', '"South Africa"'), ('GS', '"South Georgia & South Sandwich Islands"'), ('KR', '"South Korea"'), ('SS', '"South Sudan"'), ('ES', 'Spain'), ('LK', '"Sri Lanka"'), ('BL', '"St. BarthÃ©lemy"'), ('SH', '"St. Helena"'), ('KN', '"St. Kitts & Nevis"'), ('LC', '"St. Lucia"'), ('MF', '"St. Martin"'), ('PM', '"St. Pierre & Miquelon"'), ('VC', '"St. Vincent & Grenadines"'), ('SD', 'Sudan'), ('SR', 'Suriname'), ('SJ', '"Svalbard & Jan Mayen"'), ('SE', 'Sweden'), ('CH', 'Switzerland'), ('SY', 'Syria'), ('TW', 'Taiwan'), ('TJ', 'Tajikistan'), ('TZ', 'Tanzania'), ('TH', 'Thailand'), ('TL', 'Timor-Leste'), ('TG', 'Togo'), ('TK', 'Tokelau'), ('TO', 'Tonga'), ('TT', '"Trinidad & Tobago"'), ('TN', 'Tunisia'), ('TR', 'Turkey'), ('TM', 'Turkmenistan'), ('TC', '"Turks & Caicos Islands"'), ('TV', 'Tuvalu'), ('UM', '"U.S. Outlying Islands"'), ('VI', '"U.S. Virgin Islands"'), ('UG', 'Uganda'), ('UA', 'Ukraine'), ('AE', '"United Arab Emirates"'), ('GB', '"United Kingdom"'), ('US', '"United States"'), ('UY', 'Uruguay'), ('UZ', 'Uzbekistan'), ('VU', 'Vanuatu'), ('VA', '"Vatican City"'), ('VE', 'Venezuela'), ('VN', 'Vietnam'), ('WF', '"Wallis & Futuna"'), ('EH', '"Western Sahara"'), ('YE', 'Yemen'), ('ZM', 'Zambia'), ('ZW', 'Zimbabwe')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='country_of_residence',
            field=models.CharField(blank=True, choices=[('AF', 'Afghanistan'), ('AX', '"Ã…land Islands"'), ('AL', 'Albania'), ('DZ', 'Algeria'), ('AS', '"American Samoa"'), ('AD', 'Andorra'), ('AO', 'Angola'), ('AI', 'Anguilla'), ('AQ', 'Antarctica'), ('AG', '"Antigua & Barbuda"'), ('AR', 'Argentina'), ('AM', 'Armenia'), ('AW', 'Aruba'), ('AU', 'Australia'), ('AT', 'Austria'), ('AZ', 'Azerbaijan'), ('BS', 'Bahamas'), ('BH', 'Bahrain'), ('BD', 'Bangladesh'), ('BB', 'Barbados'), ('BY', 'Belarus'), ('BE', 'Belgium'), ('BZ', 'Belize'), ('BJ', 'Benin'), ('BM', 'Bermuda'), ('BT', 'Bhutan'), ('BO', 'Bolivia'), ('BA', '"Bosnia & Herzegovina"'), ('BW', 'Botswana'), ('BV', '"Bouvet Island"'), ('BR', 'Brazil'), ('IO', '"British Indian Ocean Territory"'), ('VG', '"British Virgin Islands"'), ('BN', 'Brunei'), ('BG', 'Bulgaria'), ('BF', '"Burkina Faso"'), ('BI', 'Burundi'), ('KH', 'Cambodia'), ('CM', 'Cameroon'), ('CA', 'Canada'), ('CV', '"Cape Verde"'), ('BQ', '"Caribbean Netherlands"'), ('KY', '"Cayman Islands"'), ('CF', '"Central African Republic"'), ('TD', 'Chad'), ('CL', 'Chile'), ('CN', 'China'), ('CX', '"Christmas Island"'), ('CC', '"Cocos (Keeling) Islands"'), ('CO', 'Colombia'), ('KM', 'Comoros'), ('CG', '"Congo - Brazzaville"'), ('CD', '"Congo - Kinshasa"'), ('CK', '"Cook Islands"'), ('CR', '"Costa Rica"'), ('CI', '"CÃ´te dâ€™Ivoire"'), ('HR', 'Croatia'), ('CU', 'Cuba'), ('CW', 'CuraÃ§ao'), ('CY', 'Cyprus'), ('CZ', 'Czechia'), ('DK', 'Denmark'), ('DJ', 'Djibouti'), ('DM', 'Dominica'), ('DO', '"Dominican Republic"'), ('EC', 'Ecuador'), ('EG', 'Egypt'), ('SV', '"El Salvador"'), ('GQ', '"Equatorial Guinea"'), ('ER', 'Eritrea'), ('EE', 'Estonia'), ('SZ', 'Eswatini'), ('ET', 'Ethiopia'), ('FK', '"Falkland Islands"'), ('FO', '"Faroe Islands"'), ('FJ', 'Fiji'), ('FI', 'Finland'), ('FR', 'France'), ('GF', '"French Guiana"'), ('PF', '"French Polynesia"'), ('TF', '"French Southern Territories"'), ('GA', 'Gabon'), ('GM', 'Gambia'), ('GE', 'Georgia'), ('DE', 'Germany'), ('GH', 'Ghana'), ('GI', 'Gibraltar'), ('GR', 'Greece'), ('GL', 'Greenland'), ('GD', 'Grenada'), ('GP', 'Guadeloupe'), ('GU', 'Guam'), ('GT', 'Guatemala'), ('GG', 'Guernsey'), ('GN', 'Guinea'), ('GW', 'Guinea-Bissau'), ('GY', 'Guyana'), ('HT', 'Haiti'), ('HM', '"Heard & McDonald Islands"'), ('HN', 'Honduras'), ('HK', '"Hong Kong SAR China"'), ('HU', 'Hungary'), ('IS', 'Iceland'), ('IN', 'India'), ('ID', 'Indonesia'), ('IR', 'Iran'), ('IQ', 'Iraq'), ('IE', 'Ireland'), ('IM', '"Isle of Man"'), ('IL', 'Israel'), ('IT', 'Italy'), ('JM', 'Jamaica'), ('JP', 'Japan'), ('JE', 'Jersey'), ('JO', 'Jordan'), ('KZ', 'Kazakhstan'), ('KE', 'Kenya'), ('KI', 'Kiribati'), ('KW', 'Kuwait'), ('KG', 'Kyrgyzstan'), ('LA', 'Laos'), ('LV', 'Latvia'), ('LB', 'Lebanon'), ('LS', 'Lesotho'), ('LR', 'Liberia'), ('LY', 'Libya'), ('LI', 'Liechtenstein'), ('LT', 'Lithuania'), ('LU', 'Luxembourg'), ('MO', '"Macao SAR China"'), ('MG', 'Madagascar'), ('MW', 'Malawi'), ('MY', 'Malaysia'), ('MV', 'Maldives'), ('ML', 'Mali'), ('MT', 'Malta'), ('MH', '"Marshall Islands"'), ('MQ', 'Martinique'), ('MR', 'Mauritania'), ('MU', 'Mauritius'), ('YT', 'Mayotte'), ('MX', 'Mexico'), ('FM', 'Micronesia'), ('MD', 'Moldova'), ('MC', 'Monaco'), ('MN', 'Mongolia'), ('ME', 'Montenegro'), ('MS', 'Montserrat'), ('MA', 'Morocco'), ('MZ', 'Mozambique'), ('MM', '"Myanmar (Burma)"'), ('NA', 'Namibia'), ('NR', 'Nauru'), ('NP', 'Nepal'), ('NL', 'Netherlands'), ('NC', '"New Caledonia"'), ('NZ', '"New Zealand"'), ('NI', 'Nicaragua'), ('NE', 'Niger'), ('NG', 'Nigeria'), ('NU', 'Niue'), ('NF', '"Norfolk Island"'), ('KP', '"North Korea"'), ('MK', '"North Macedonia"'), ('MP', '"Northern Mariana Islands"'), ('NO', 'Norway'), ('OM', 'Oman'), ('PK', 'Pakistan'), ('PW', 'Palau'), ('PS', '"Palestinian Territories"'), ('PA', 'Panama'), ('PG', '"Papua New Guinea"'), ('PY', 'Paraguay'), ('PE', 'Peru'), ('PH', 'Philippines'), ('PN', '"Pitcairn Islands"'), ('PL', 'Poland'), ('PT', 'Portugal'), ('PR', '"Puerto Rico"'), ('QA', 'Qatar'), ('RE', 'RÃ©union'), ('RO', 'Romania'), ('RU', 'Russia'), ('RW', 'Rwanda'), ('WS', 'Samoa'), ('SM', '"San Marino"'), ('ST', '"SÃ£o TomÃ© & PrÃ\xadncipe"'), ('SA', '"Saudi Arabia"'), ('SN', 'Senegal'), ('RS', 'Serbia'), ('SC', 'Seychelles'), ('SL', '"Sierra Leone"'), ('SG', 'Singapore'), ('SX', '"Sint Maarten"'), ('SK', 'Slovakia'), ('SI', 'Slovenia'), ('SB', '"Solomon Islands"'), ('SO', 'Somalia'), ('ZA', '"South Africa"'), ('GS', '"South Georgia & South Sandwich Islands"'), ('KR', '"South Korea"'), ('SS', '"South Sudan"'), ('ES', 'Spain'), ('LK', '"Sri Lanka"'), ('BL', '"St. BarthÃ©lemy"'), ('SH', '"St. Helena"'), ('KN', '"St. Kitts & Nevis"'), ('LC', '"St. Lucia"'), ('MF', '"St. Martin"'), ('PM', '"St. Pierre & Miquelon"'), ('VC', '"St. Vincent & Grenadines"'), ('SD', 'Sudan'), ('SR', 'Suriname'), ('SJ', '"Svalbard & Jan Mayen"'), ('SE', 'Sweden'), ('CH', 'Switzerland'), ('SY', 'Syria'), ('TW', 'Taiwan'), ('TJ', 'Tajikistan'), ('TZ', 'Tanzania'), ('TH', 'Thailand'), ('TL', 'Timor-Leste'), ('TG', 'Togo'), ('TK', 'Tokelau'), ('TO', 'Tonga'), ('TT', '"Trinidad & Tobago"'), ('TN', 'Tunisia'), ('TR', 'Turkey'), ('TM', 'Turkmenistan'), ('TC', '"Turks & Caicos Islands"'), ('TV', 'Tuvalu'), ('UM', '"U.S. Outlying Islands"'), ('VI', '"U.S. Virgin Islands"'), ('UG', 'Uganda'), ('UA', 'Ukraine'), ('AE', '"United Arab Emirates"'), ('GB', '"United Kingdom"'), ('US', '"United States"'), ('UY', 'Uruguay'), ('UZ', 'Uzbekistan'), ('VU', 'Vanuatu'), ('VA', '"Vatican City"'), ('VE', 'Venezuela'), ('VN', 'Vietnam'), ('WF', '"Wallis & Futuna"'), ('EH', '"Western Sahara"'), ('YE', 'Yemen'), ('ZM', 'Zambia'), ('ZW', 'Zimbabwe')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='create_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='data_link',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='db_status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='drivers_license_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='drivers_license_state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email_alerts',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_time_status',
            field=models.CharField(blank=True, choices=[('F', 'Full Time'), ('P', 'Part Time')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='level_of_education',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('W', 'Widowed')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_middle_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_name_suffix',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_primary_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_secondary_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='portal_access',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='preferred_first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='preferred_last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='preferred_middle_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='preferred_name_suffix',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sevis_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='ssn',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sso',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='stage_status',
            field=models.CharField(blank=True, choices=[('check-in', 'Check In'), ('continuing', 'Continuing'), ('pre-arrival', 'Pre Arrival'), ('post-grad', 'Postcompletion Graduated')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='tax_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
